### ISSUE TITLE
Custom route name

### ISSUE THREAD

**Issue by adrienpoly** [kobaltz/mission_control-servers#10]
Hello 

Thanks for this project really like where it is going

I am trying to set it up and wanted to use a simpler route than `mission_control-servers` 

```
mount MissionControl::Servers::Engine => "/servers"
```

As fare as I could tell this was creating a few side effects and I had to roll back to the official route name.

When using a custom route the link to install is :  

`curl -sSL https://example.com/servers/projects/xxxxxxxxxx/script | sh`

but this link 404 I had to manually change it to 

`curl -sSL https://example.com/mission_control-servers/projects/xxxxxxxxxx/script | sh`

With that I could install the but it doesn't work the first attend to send data fails (I suppose their is once again the route issue)

## Solution 

rolled back to the official route name for now

**Comment by kobaltz** [comment]
Hmmm. that's strange. Did you have any constraints or anything? I just tested this out in a new Rails 7 app and was unable to replicate the problem. Do you have a sample app that you would be able to share so I can try to figure out the issue?

**Comment by adrienpoly** [comment]
Sorry my bad I tested again on[ an open source repo](https://github.com/adrienpoly/daisy-on-rails/pull/8) and it works fine. 

I didn't set it up properly the first time.

I had :

```ruby
MissionControl::Servers::RoutingHelpers.add_public_routes_helper(self)

authenticate :admin do
  mount MissionControl::Servers::Engine => "servers"
end
```

rather than 

```ruby
MissionControl::Servers::RoutingHelpers.add_public_routes_helper(self, "servers")

authenticate :admin do
  mount MissionControl::Servers::Engine => "servers"
end
```
